services:
  db:
    image: postgres:15.3
    container_name: uu_db
    environment:
       POSTGRES_HOST_AUTH_METHOD: trust
       POSTGRES_PASSWORD: postgres
       POSTGRES_USER: postgres
       POSTGRES_DB: postgres
  adminer:
    image: adminer:4.8.1
    ports:
      - 8080:8080
    container_name: uu_adminer
  web:
    build: .
    command: python3 untraceableuniversity/manage.py runserver 0.0.0.0:8888
    volumes:
      - .:/code
    ports:
      - 8888:8888
    depends_on:
      - db
    container_name: uu_web
